### ISSUE TITLE
Compatibility with Seurat v5 Objects

### ISSUE THREAD

**Issue by afonsoguerra** [hms-dbmi/dseqr#205]
Thanks for the software that is very useful for data exploration and hypothesis generation.

I am currently using the docker version, and it gives errors if I try to import a Seurat 5 object. The same data goes in fine as an SCE object. Any plans to add Seurat5 support.

Thanks!

**Comment by alexvpickering** [comment]
Glad to hear its useful to you @afonsoguerra!

 This isn't currently a priority but I will think about it since you ask. In the meantime I would suggest either converting to SCE as you mentioned or casting `Assay5` slots as `Assay`'s ([see here](https://github.com/satijalab/seurat/issues/7409))

**Comment by alexvpickering** [comment]
@afonsoguerra - sorry for the large delay. This should work now with either `Assay5` or `Assay` but let me know if you encounter any other issues
